### ISSUE TITLE
An error occurred while running the project using linux docker dotnet

### ISSUE THREAD

**Issue by GreenHatHG** [bburman/Twelve21.PasswordStorage#1]
I installed docker in debian9 and then pulled the docker image of dotnet.

```
docker pull microsoft/dotnet
```

Then git clone the project to /root.

Then run docker and exec it.

```
docker run -itd --name mc -v /root/Twelve21.PasswordStorage:/app microsoft/dotnet bash
docker exec -it mc bash
cd /app
```

An error occurred while running after build

![error.png](https://i.loli.net/2019/08/24/wHfJauzPgnTc6By.png)

**Comment by bburman** [comment]
This should be resolved now. I updated to .NET 5 and included the processor-agnostic check fix. You'll need to pull the docker image from mcr.microsoft.com/dotnet/sdk. Thanks for the feedback and I apologize for the delay!
